# Generated by AI
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt

def plot_all_results(results_dir='./results'):
    # 获取所有的 csv 文件路径
    csv_files = glob.glob(os.path.join(results_dir, '*.csv'))
    
    if not csv_files:
        print(f"在 {results_dir} 目录下没有找到 CSV 文件！请先运行训练脚本。")
        return

    # 初始化 4 张图的 Figure 和 Axes
    plt.style.use('seaborn-v0_8-whitegrid') # 使用美观的网格样式
    
    fig_train_acc, ax_train_acc = plt.subplots(figsize=(10, 6))
    fig_train_loss, ax_train_loss = plt.subplots(figsize=(10, 6))
    fig_val_acc, ax_val_acc = plt.subplots(figsize=(10, 6))
    fig_val_loss, ax_val_loss = plt.subplots(figsize=(10, 6))

    print(f"找到 {len(csv_files)} 个实验结果，开始绘图...")

    # 遍历每一个 csv 文件
    for file in sorted(csv_files):
        # 提取文件名作为图例名称（去掉 .csv 后缀）
        exp_name = os.path.basename(file).replace('.csv', '')
        
        # 读取数据
        df = pd.read_csv(file)
        epochs = df['Epoch']
        
        # 绘制四条曲线，使用自动分配的颜色，并绑定标签
        ax_train_acc.plot(epochs, df['Train Acc'], marker='o', label=exp_name)
        ax_train_loss.plot(epochs, df['Train Loss'], marker='o', label=exp_name)
        ax_val_acc.plot(epochs, df['Val Acc'], marker='o', label=exp_name)
        ax_val_loss.plot(epochs, df['Val Loss'], marker='o', label=exp_name)

    # --- 配置 Train Accuracy 图像 ---
    ax_train_acc.set_title('Training Accuracy', fontsize=16)
    ax_train_acc.set_xlabel('Epochs', fontsize=12)
    ax_train_acc.set_ylabel('Accuracy', fontsize=12)
    ax_train_acc.set_ylim(0.90, 1.00) # 按要求限制上下限为 90% - 100%
    ax_train_acc.legend(fontsize=10)
    fig_train_acc.savefig(os.path.join(results_dir, 'train_acc.png'), dpi=300, bbox_inches='tight')

    # --- 配置 Train Loss 图像 ---
    ax_train_loss.set_title('Training Loss', fontsize=16)
    ax_train_loss.set_xlabel('Epochs', fontsize=12)
    ax_train_loss.set_ylabel('Loss', fontsize=12)
    ax_train_loss.set_ylim(0.0, 0.4) # 按要求限制上下限为 0 - 0.4
    ax_train_loss.legend(fontsize=10)
    fig_train_loss.savefig(os.path.join(results_dir, 'train_loss.png'), dpi=300, bbox_inches='tight')

    # --- 配置 Validation Accuracy 图像 ---
    ax_val_acc.set_title('Validation Accuracy', fontsize=16)
    ax_val_acc.set_xlabel('Epochs', fontsize=12)
    ax_val_acc.set_ylabel('Accuracy', fontsize=12)
    ax_val_acc.set_ylim(0.90, 1.00) # 验证集准确率同样限制在 90% - 100%
    ax_val_acc.legend(fontsize=10)
    fig_val_acc.savefig(os.path.join(results_dir, 'val_acc.png'), dpi=300, bbox_inches='tight')

    # --- 配置 Validation Loss 图像 ---
    ax_val_loss.set_title('Validation Loss', fontsize=16)
    ax_val_loss.set_xlabel('Epochs', fontsize=12)
    ax_val_loss.set_ylabel('Loss', fontsize=12)
    ax_val_loss.set_ylim(0.0, 0.4) # 验证集 Loss 限制在 0 - 0.4
    ax_val_loss.legend(fontsize=10)
    fig_val_loss.savefig(os.path.join(results_dir, 'val_loss.png'), dpi=300, bbox_inches='tight')

    print(f"绘图完成！四张图片已保存至 {results_dir} 目录下。")

if __name__ == '__main__':
    plot_all_results('./results')